[package]
name = "rs-txtar"
description = "Rust implementation of the txtar format"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
